// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace window
{
	public partial class PreferencesWindowController : NSViewController
	{
		public PreferencesWindowController(IntPtr handle) : base(handle)
		{
		}
	}
}
