// This file has been autogenerated from a class added in the UI designer.
namespace window
{
	public partial class WindowController : NSWindowController
	{
		public WindowController(IntPtr handle) : base(handle)
		{
			
		}
	}
}
